
{-
Problem 2 http://projecteuler.net/index.php?section=problems&id=2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
-}

fib :: [Int]
fib = 1 : 2 : [ a + b | (a, b) <- zip fib (tail fib)]

main = putStrLn . show $
  sum (filter even (takeWhile (<=4000000) fib))
