######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 10 05:30:27 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += multi_map.cpp
